// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ5Cj1uzz5eGCJzIFSqlNjg2WkW7z5xy8',
    appId: '1:266007843193:web:53f012180df99c25339fa8',
    messagingSenderId: '266007843193',
    projectId: 'fruit-hub-beba7',
    authDomain: 'fruit-hub-beba7.firebaseapp.com',
    storageBucket: 'fruit-hub-beba7.firebasestorage.app',
    measurementId: 'G-SFD4G1CL7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8EMr6H50eSFlvK5VFZAkhOMg3WdlAGjQ',
    appId: '1:266007843193:android:365a44f47fc415ab339fa8',
    messagingSenderId: '266007843193',
    projectId: 'fruit-hub-beba7',
    storageBucket: 'fruit-hub-beba7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-P6pRURVMlmLCwSjp0dOokdpR2q_S79E',
    appId: '1:266007843193:ios:bc559bc311911780339fa8',
    messagingSenderId: '266007843193',
    projectId: 'fruit-hub-beba7',
    storageBucket: 'fruit-hub-beba7.firebasestorage.app',
    iosBundleId: 'com.example.frutsECommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-P6pRURVMlmLCwSjp0dOokdpR2q_S79E',
    appId: '1:266007843193:ios:bc559bc311911780339fa8',
    messagingSenderId: '266007843193',
    projectId: 'fruit-hub-beba7',
    storageBucket: 'fruit-hub-beba7.firebasestorage.app',
    iosBundleId: 'com.example.frutsECommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ5Cj1uzz5eGCJzIFSqlNjg2WkW7z5xy8',
    appId: '1:266007843193:web:d3763397711a02ca339fa8',
    messagingSenderId: '266007843193',
    projectId: 'fruit-hub-beba7',
    authDomain: 'fruit-hub-beba7.firebaseapp.com',
    storageBucket: 'fruit-hub-beba7.firebasestorage.app',
    measurementId: 'G-DT5C5KV6YP',
  );
}
