import 'package:fruts_e_commerce/core/model/product_model.dart';
import 'package:fruts_e_commerce/core/services/firestore_service.dart';
import 'package:fruts_e_commerce/core/utils/backend_endpoint.dart';

Future<void> seedProducts() async {
  final firestoreService = FirestoreService();
  
  final List<ProductModel> products = [
    ProductModel(
      name: 'فراولة',
      price: 25,
      code: 'F001',
      description: 'فراولة طازجة وعضوية، غنية بفيتامين سي.',
      imageUrl: 'https://images.unsplash.com/photo-1518635017498-87f514b751ba?q=80&w=600&auto=format&fit=crop',
      isFeatured: true,
      expirationMonths: 1,
      isOrganic: true,
      numberOfCalories: 32,
      unitAmount: 1,
      sellingCount: 150,
      reviews: [],
    ),
    ProductModel(
      name: 'موز',
      price: 15,
      code: 'F002',
      description: 'موز أصفر طازج، مثالي للطاقة السريعة.',
      imageUrl: 'https://images.unsplash.com/photo-1528825871115-3581a5387919?q=80&w=600&auto=format&fit=crop',
      isFeatured: true,
      expirationMonths: 1,
      isOrganic: false,
      numberOfCalories: 89,
      unitAmount: 1,
      sellingCount: 300,
      reviews: [],
    ),
    ProductModel(
      name: 'تفاح أحمر',
      price: 30,
      code: 'F003',
      description: 'تفاح أحمر مقرمش، طازج ومقطوف بعناية.',
      imageUrl: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6fac6?q=80&w=600&auto=format&fit=crop',
      isFeatured: false,
      expirationMonths: 2,
      isOrganic: true,
      numberOfCalories: 52,
      unitAmount: 1,
      sellingCount: 210,
      reviews: [],
    ),
    ProductModel(
      name: 'مانجو',
      price: 45,
      code: 'F004',
      description: 'مانجو استوائية حلوة وعصرية.',
      imageUrl: 'https://images.unsplash.com/photo-1553279768-865429fa0078?q=80&w=600&auto=format&fit=crop',
      isFeatured: true,
      expirationMonths: 1,
      isOrganic: true,
      numberOfCalories: 60,
      unitAmount: 1,
      sellingCount: 400,
      reviews: [],
    ),
    ProductModel(
      name: 'برتقال',
      price: 20,
      code: 'F005',
      description: 'برتقال سكري طازج من المزرعة.',
      imageUrl: 'https://images.unsplash.com/photo-1549888834-3ec93abae044?q=80&w=600&auto=format&fit=crop',
      isFeatured: false,
      expirationMonths: 1,
      isOrganic: false,
      numberOfCalories: 47,
      unitAmount: 1,
      sellingCount: 180,
      reviews: [],
    ),
    ProductModel(
      name: 'عنب أرجواني',
      price: 35,
      code: 'F006',
      description: 'عنب طازج ولذيذ، خالي من البذور.',
      imageUrl: 'https://images.unsplash.com/photo-1596363505729-4190a9506133?q=80&w=600&auto=format&fit=crop',
      isFeatured: true,
      expirationMonths: 1,
      isOrganic: true,
      numberOfCalories: 69,
      unitAmount: 1,
      sellingCount: 250,
      reviews: [],
    ),
    ProductModel(
      name: 'أناناس',
      price: 40,
      code: 'F007',
      description: 'أناناس استوائي ذو جودة عالية.',
      imageUrl: 'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?q=80&w=600&auto=format&fit=crop',
      isFeatured: false,
      expirationMonths: 1,
      isOrganic: true,
      numberOfCalories: 50,
      unitAmount: 1,
      sellingCount: 90,
      reviews: [],
    ),
    ProductModel(
      name: 'بطيخ',
      price: 50,
      code: 'F008',
      description: 'بطيخ أحمر حلو منعش لفصل الصيف.',
      imageUrl: 'https://images.unsplash.com/photo-1589984662646-e7b2e4962f18?q=80&w=600&auto=format&fit=crop',
      isFeatured: true,
      expirationMonths: 1,
      isOrganic: false,
      numberOfCalories: 30,
      unitAmount: 1,
      sellingCount: 150,
      reviews: [],
    ),
    ProductModel(
      name: 'كيوي',
      price: 55,
      code: 'F009',
      description: 'كيوي طازج مليء بالطاقة والفيتامينات.',
      imageUrl: 'https://images.unsplash.com/photo-1585059895524-72359e06133a?q=80&w=600&auto=format&fit=crop',
      isFeatured: false,
      expirationMonths: 1,
      isOrganic: true,
      numberOfCalories: 61,
      unitAmount: 1,
      sellingCount: 110,
      reviews: [],
    ),
    ProductModel(
      name: 'توت أزرق',
      price: 80,
      code: 'F010',
      description: 'توت أزرق غني بمضادات الأكسدة.',
      imageUrl: 'https://images.unsplash.com/photo-1498557850523-fd3d118b962e?q=80&w=600&auto=format&fit=crop',
      isFeatured: true,
      expirationMonths: 1,
      isOrganic: true,
      numberOfCalories: 57,
      unitAmount: 1,
      sellingCount: 320,
      reviews: [],
    ),
  ];

  for (var product in products) {
    await firestoreService.addData(
      path: BackendEndpoint.getProducts,
      data: product.tojson(),
    );
  }
}
